package cmd

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGetTeamsBySeason(t *testing.T) {
	teamsBySeason, err := GetTeamsBySeason("./test_data")
	require.NoError(t, err)
	expectedTeamsBySeason := ByTeamsBySeason{
		m: map[string]map[int]*Season{
			"SFN": {
				2000: &Season{
					Franchise: "SFN",
					Team:      "SFN",
					Year:      2000,
					Games: []TeamGame{
						{
							Date:               time.Date(2000, time.July, 23, 0, 0, 0, 0, time.UTC),
							Team:               "SFN",
							Franchise:          "SFN",
							OpponentTeam:       "LAN",
							OpponentFranchise:  "LAN",
							OpponentGameNumber: 1,
							TeamGameNumber:     1,
							OpponentScore:      8,
							TeamScore:          1,
							ForfeitInfo:        "",
							OpponentLineScore:  "00010052x",
							TeamLineScore:      "001000000",
							Result:             Loss,
						},
						{
							Date:               time.Date(2000, time.July, 23, 0, 0, 0, 0, time.UTC),
							Team:               "SFN",
							Franchise:          "SFN",
							OpponentTeam:       "LAN",
							OpponentFranchise:  "LAN",
							OpponentGameNumber: 2,
							TeamGameNumber:     2,
							OpponentScore:      1,
							TeamScore:          4,
							ForfeitInfo:        "",
							OpponentLineScore:  "10000x",
							TeamLineScore:      "201010",
							Result:             Win,
						},
					},
				},
				2001: &Season{
					Franchise: "SFN",
					Team:      "SFN",
					Year:      2001,
					Games: []TeamGame{
						{
							Date:               time.Date(2001, time.July, 23, 0, 0, 0, 0, time.UTC),
							Team:               "SFN",
							Franchise:          "SFN",
							OpponentTeam:       "BRO",
							OpponentFranchise:  "LAN",
							OpponentGameNumber: 1,
							TeamGameNumber:     1,
							OpponentScore:      5,
							TeamScore:          3,
							ForfeitInfo:        "",
							OpponentLineScore:  "00000050x",
							TeamLineScore:      "001010100",
							Result:             Loss,
						},
						{
							Date:               time.Date(2001, time.July, 23, 0, 0, 0, 0, time.UTC),
							Team:               "SFN",
							Franchise:          "SFN",
							OpponentTeam:       "BRO",
							OpponentFranchise:  "LAN",
							OpponentGameNumber: 2,
							TeamGameNumber:     2,
							OpponentScore:      1,
							TeamScore:          24,
							ForfeitInfo:        "",
							OpponentLineScore:  "10000x",
							TeamLineScore:      "(20)01012",
							Result:             Win,
						},
					},
				},
			},
			"LAN": {
				2000: &Season{
					Franchise: "LAN",
					Team:      "LAN",
					Year:      2000,
					Games: []TeamGame{
						{
							Date:               time.Date(2000, time.July, 23, 0, 0, 0, 0, time.UTC),
							Team:               "LAN",
							Franchise:          "LAN",
							OpponentTeam:       "SFN",
							OpponentFranchise:  "SFN",
							OpponentGameNumber: 1,
							TeamGameNumber:     1,
							OpponentScore:      1,
							TeamScore:          8,
							ForfeitInfo:        "",
							TeamLineScore:      "00010052x",
							OpponentLineScore:  "001000000",
							Result:             Win,
						},
						{
							Date:               time.Date(2000, time.July, 23, 0, 0, 0, 0, time.UTC),
							Team:               "LAN",
							Franchise:          "LAN",
							OpponentTeam:       "SFN",
							OpponentFranchise:  "SFN",
							OpponentGameNumber: 2,
							TeamGameNumber:     2,
							OpponentScore:      4,
							TeamScore:          1,
							ForfeitInfo:        "",
							OpponentLineScore:  "201010",
							TeamLineScore:      "10000x",
							Result:             Loss,
						},
					},
				},
				2001: &Season{
					Franchise: "LAN",
					Team:      "BRO",
					Year:      2001,
					Games: []TeamGame{
						{
							Date:               time.Date(2001, time.July, 23, 0, 0, 0, 0, time.UTC),
							Team:               "BRO",
							Franchise:          "LAN",
							OpponentTeam:       "SFN",
							OpponentFranchise:  "SFN",
							OpponentGameNumber: 1,
							TeamGameNumber:     1,
							OpponentScore:      3,
							TeamScore:          5,
							ForfeitInfo:        "",
							OpponentLineScore:  "001010100",
							TeamLineScore:      "00000050x",
							Result:             Win,
						},
						{
							Date:               time.Date(2001, time.July, 23, 0, 0, 0, 0, time.UTC),
							Team:               "BRO",
							Franchise:          "LAN",
							OpponentTeam:       "SFN",
							OpponentFranchise:  "SFN",
							OpponentGameNumber: 2,
							TeamGameNumber:     2,
							OpponentScore:      24,
							TeamScore:          1,
							ForfeitInfo:        "",
							OpponentLineScore:  "(20)01012",
							TeamLineScore:      "10000x",
							Result:             Loss,
						},
					},
				},
			},
			"MIL": {
				2000: &Season{
					Franchise: "MIL",
					Team:      "MIL",
					Year:      2000,
					Games: []TeamGame{
						{
							Date:               time.Date(2000, time.July, 24, 0, 0, 0, 0, time.UTC),
							Team:               "MIL",
							Franchise:          "MIL",
							OpponentTeam:       "CHN",
							OpponentFranchise:  "CHN",
							OpponentGameNumber: 1,
							TeamGameNumber:     1,
							OpponentScore:      3,
							TeamScore:          0,
							ForfeitInfo:        "",
							TeamLineScore:      "000000000",
							OpponentLineScore:  "00200001x",
							Result:             Loss,
						},
						{
							Date:               time.Date(2000, time.July, 24, 0, 0, 0, 0, time.UTC),
							Team:               "MIL",
							Franchise:          "MIL",
							OpponentTeam:       "CHN",
							OpponentFranchise:  "CHN",
							OpponentGameNumber: 2,
							TeamGameNumber:     2,
							OpponentScore:      7,
							TeamScore:          1,
							ForfeitInfo:        "",
							OpponentLineScore:  "20101120x",
							TeamLineScore:      "000100000",
							Result:             Loss,
						},
					},
				},
				2001: &Season{
					Franchise: "MIL",
					Team:      "MIL",
					Year:      2001,
					Games: []TeamGame{
						{
							Date:               time.Date(2001, time.July, 24, 0, 0, 0, 0, time.UTC),
							Team:               "MIL",
							Franchise:          "MIL",
							OpponentTeam:       "CHN",
							OpponentFranchise:  "CHN",
							OpponentGameNumber: 1,
							TeamGameNumber:     1,
							TeamScore:          1,
							OpponentScore:      3,
							ForfeitInfo:        "",
							OpponentLineScore:  "00200001x",
							TeamLineScore:      "001000000",
							Result:             Loss,
						},
						{
							Date:               time.Date(2001, time.July, 24, 0, 0, 0, 0, time.UTC),
							Team:               "MIL",
							Franchise:          "MIL",
							OpponentTeam:       "CHN",
							OpponentFranchise:  "CHN",
							OpponentGameNumber: 2,
							TeamGameNumber:     2,
							OpponentScore:      7,
							TeamScore:          15,
							ForfeitInfo:        "",
							OpponentLineScore:  "20101120x",
							TeamLineScore:      "000(10)02030",
							Result:             Win,
						},
					},
				},
			},
			"CHN": {
				2000: &Season{
					Franchise: "CHN",
					Team:      "CHN",
					Year:      2000,
					Games: []TeamGame{
						{
							Date:               time.Date(2000, time.July, 24, 0, 0, 0, 0, time.UTC),
							Team:               "CHN",
							Franchise:          "CHN",
							OpponentTeam:       "MIL",
							OpponentFranchise:  "MIL",
							OpponentGameNumber: 1,
							TeamGameNumber:     1,
							OpponentScore:      0,
							TeamScore:          3,
							ForfeitInfo:        "",
							TeamLineScore:      "00200001x",
							OpponentLineScore:  "000000000",
							Result:             Win,
						},
						{
							Date:               time.Date(2000, time.July, 24, 0, 0, 0, 0, time.UTC),
							Team:               "CHN",
							Franchise:          "CHN",
							OpponentTeam:       "MIL",
							OpponentFranchise:  "MIL",
							OpponentGameNumber: 2,
							TeamGameNumber:     2,
							OpponentScore:      1,
							TeamScore:          7,
							ForfeitInfo:        "",
							OpponentLineScore:  "000100000",
							TeamLineScore:      "20101120x",
							Result:             Win,
						},
					},
				},
				2001: &Season{
					Franchise: "CHN",
					Team:      "CHN",
					Year:      2001,
					Games: []TeamGame{
						{
							Date:               time.Date(2001, time.July, 24, 0, 0, 0, 0, time.UTC),
							Team:               "CHN",
							Franchise:          "CHN",
							OpponentTeam:       "MIL",
							OpponentFranchise:  "MIL",
							OpponentGameNumber: 1,
							TeamGameNumber:     1,
							TeamScore:          3,
							OpponentScore:      1,
							ForfeitInfo:        "",
							OpponentLineScore:  "001000000",
							TeamLineScore:      "00200001x",
							Result:             Win,
						},
						{
							Date:               time.Date(2001, time.July, 24, 0, 0, 0, 0, time.UTC),
							Team:               "CHN",
							Franchise:          "CHN",
							OpponentTeam:       "MIL",
							OpponentFranchise:  "MIL",
							OpponentGameNumber: 2,
							TeamGameNumber:     2,
							OpponentScore:      15,
							TeamScore:          7,
							ForfeitInfo:        "",
							OpponentLineScore:  "000(10)02030",
							TeamLineScore:      "20101120x",
							Result:             Loss,
						},
					},
				},
			}},
	}
	assert.Equal(t, expectedTeamsBySeason.m, teamsBySeason.m)
}
